name: Extend ClickHouse Image
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: AWS ECR
      uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      env:
        AWS_REGION: us-east-1
        AWS_ECR_REPO: clickhouse-server
      with:
        access_key_id: ${{ secrets.BUILD_BOT_AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.BUILD_BOT_AWS_ACCESS_SECRET }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        region: ${{ env.AWS_REGION }}
        repo: ${{ env.AWS_ECR_REPO }}
        tags: ${{ github.sha }}
        path: ./docker/debug
        create_repo: true
